#!/bin/bash

# specify the case you want to test here!
case=case4
version=basic
# Build and run your final project!
NTHU_bike:
	g++ -g -std=c++11 -o ./bin/main ./src/main.cpp
	./bin/main $(case) $(version)